<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admins-MBP-111.lan" failures="1" tests="11" name="api.tests.TestsOrderFlow" time="5.409" errors="0" timestamp="2024-12-18T12:13:36 IST" skipped="7">
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowCreateShipment" time="1.127">
    <failure message="Test failed due to unexpected Status:- INITIATEDa" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected Status:- INITIATEDa
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at api.tests.TestsOrderFlow.testOrderFlowCreateShipment(TestsOrderFlow.java:184)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testOrderFlowCreateShipment -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowDispatch" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowDispatch -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowAccceptItem1QC" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowAccceptItem1QC -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowMarkPacked" time="0.656"/>
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowAccceptItem2QC" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowAccceptItem2QC -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowActionCompleteQC" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowActionCompleteQC -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowDeliver" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowDeliver -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowCompleteQC" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowCompleteQC -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowInventorySettlement" time="0.000">
    <skipped/>
  </testcase> <!-- testOrderFlowInventorySettlement -->
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowBatchAssign" time="0.562"/>
  <testcase classname="api.tests.TestsOrderFlow" name="testOrderFlowcreateOrder" time="3.064"/>
</testsuite> <!-- api.tests.TestsOrderFlow -->
